### ISSUE TITLE
large exports don't work

### ISSUE THREAD

**Issue by javisantana** [CartoDB/CartoDB-SQL-API#204]
some exports that worked before stop working, for example:

```
https://viz2.cartodb.com/api/v1/sql?q=select%20lat,long,temp,date%20from%20ow&format=csv
```
the error is:

```
"Your query was not able to finish. Either you have too many queries running or the one you are trying to run is too expensive. Try again."
```

Sounds reasonable for me but we should provide a way to download large datasets. We could use the ``COPY`` command to stream csv or pgdump files

**Comment by rafatower** [comment]
Seems like ogr2ogr is doing a mad query that can be pretty heavy depending on the number of tables:
```
SELECT c.relname, n.nspname, c.relkind, g.f_geometry_column, g.type, g.coord_dimension, g.srid, 1, c.oid as oid, a.attnum as attnum FROM pg_class c, pg_namespace n, geometry_columns g, pg_attribute a WHERE (c.relkind in ('r','v') AND c.relname !~ '^pg_' AND c.relnamespace=n.oid AND c.relname::TEXT = g.f_table_name::TEXT AND n.nspname = g.f_table_schema AND a.attname = g.f_geometry_column AND a.attrelid = c.oid) UNION SELECT c.relname, n.nspname, c.relkind, g.f_geography_column, g.type, g.coord_dimension, g.srid, 2, c.oid as oid, a.attnum as attnum FROM pg_class c, pg_namespace n, geography_columns g, pg_attribute a WHERE (c.relkind in ('r','v') AND c.relname !~ '^pg_' AND c.relnamespace=n.oid AND c.relname::TEXT = g.f_table_name::TEXT AND n.nspname = g.f_table_schema AND a.attname = g.f_geography_column AND a.attrelid = c.oid) ORDER BY oid, attnum;
```
In my case in local it takes around 8 seconds with 480 rows. It has nested loops

**Comment by javisantana** [comment]
asked even about this

**Comment by pramsey** [comment]
Yeah, the reference to ‘geometry_columns’ in the query is a bit of a giveaway. Pretty sure it’s just looking for “all the geometry tables and views”. Probably pre-dates 2.0, since it’s pretty crazy to be joining geometry_columns (now a view on the system tables) back onto the system tables. Better just to ask it directly or to skip it entirely and ask the system tables directly.

**Comment by javisantana** [comment]
from even: 

"""
If you know the tables you want to work on, you can add " tables=foo,bar" to the
OGR connection string, which will skip this statement that lists the existing
tables.
"""

**Comment by pramsey** [comment]
I tested out the OGR version of the system table query, and a simplified one that doesn't do the join against geometry_columns, and the simple one is about 10x faster on a system with 1000 tables. That said, the OGR one didn't exceed 500ms in runtime, so wondering where the 8 *seconds* comes from.

**Comment by rochoa** [comment]
I'm reopening the issue as the fix depends on the version of gdal/ogr2ogr you are using.

**Comment by rochoa** [comment]
Dragging this into next milestone as I'm waiting for a new ogr2ogr version.

**Comment by rafatower** [comment]
I cooked a static compilation of ogr2ogr 10 days ago, is it enough?

**Comment by pramsey** [comment]
If it's from svn trunk it should have the improvements to the metadata query.

**Comment by rafatower** [comment]
This is the commit of the debian package currently in production: https://github.com/CartoDB/gdal/commit/bec046151067f3ece7eef042f0b852a750d04529

based on this commit from upstream: https://github.com/CartoDB/gdal/commit/6c6d1ac19a1c58b6c2a664dd1ddba2fbf9549d38

**Comment by rochoa** [comment]
Since [version 1.23.0](https://github.com/CartoDB/CartoDB-SQL-API/blob/1.23.0/NEWS.md#1230---2015-06-16) it's possible to configure the ogr2ogr command (command name or path) to use. Using ogr2ogr from trunk should do the trick.

A good alternative is to have `ogr2ogr2-static-bin` from `ppa:cartodb/gis` so you can keep using ogr2ogr (stable release) and start using ogr2ogr2 (ogr2ogr from trunk). That's what we are doing.

I've testing some of the scenarios that were failing before (this issue's and linked issues) and they work now so I'm finally closing this issue \o/.

Thanks to everyone involved!!
