### ISSUE TITLE
a 'no longer running' job reports as 'running' before and after a job cancel

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/CartoDB-SQL-API#293]
I set up a job to run update the_geom. Everything looked good in the POST, and checking on the status:

```bash
peschbacher:Desktop $ curl -X GET "http://envisage.cartodb.com/api/v2/sql/job/19b90278-9391-42f5-8e3b-de6c1b12fb98?api_key=abcdefghijklmnopqrstuvwxyz"
{"job_id":"19b90278-9391-42f5-8e3b-de6c1b12fb98","user":"envisage","status":"running","query":"UPDATE zillow_zhvi_2015_2016 SET the_geom = cdb_observatory.OBS_GetBoundaryById(zcta5,'\"us.census.tiger\".zcta5')","created_at":"2016-05-03T16:32:10.915Z","updated_at":"2016-05-03T16:32:59.967Z"}
```
The job ran for much longer that I expected, so I decided cancel it.  Doing so gives "Query is not running currently":
```bash
peschbacher:Desktop $ curl -X DELETE "http://envisage.cartodb.com/api/v2/sql/job/19b90278-9391-42f5-8e3b-de6c1b12fb98?api_key=abcdefghijklmnopqrstuvwxyz"
{"error":["Query is not running currently"]}
```

But getting the status again gives:
```bash
peschbacher:Desktop $ curl -X GET "http://envisage.cartodb.com/api/v2/sql/job/19b90278-9391-42f5-8e3b-de6c1b12fb98?api_key=abcdefghijklmnopqrstuvwxyz"
{"job_id":"19b90278-9391-42f5-8e3b-de6c1b12fb98","user":"envisage","status":"running","query":"UPDATE zillow_zhvi_2015_2016 SET the_geom = cdb_observatory.OBS_GetBoundaryById(zcta5,'\"us.census.tiger\".zcta5')","created_at":"2016-05-03T16:32:10.915Z","updated_at":"2016-05-03T16:32:59.967Z"}
```
Which says that the query is still running.

**Comment by dgaubert** [comment]
Thanks @ohasselblad for the detailed description.

Actually there are two issues here, first one is why a job status is still `running` in spite of isn't `running` in Postgres, and second one don't allow to cancel a job even though is not `running` on Postgres but its status is.

The first one is really hard to debug, because it depends on connections, drivers and so on (in production). I'm going to research if is something _unsual_ (it should be), or not. Anyway, I'm going to allow to cancel job regardless if the job is running on Postgres, making sure is going to be `cancelled`.
