### ISSUE TITLE
Reset pooled sessions between uses

### ISSUE THREAD

**Issue by strk** [CartoDB/CartoDB-SQL-API#98]
Pooled pgsql clients allow for a single session to survive a single request, thus setting a relation between intentionally unrelated requests (session variables may and will affect different uses).

This ticket is to ensure all session variables are reset between uses.
See DISCARD ALL postgresql command.

Not sure how easy it will be to test this with current mocha-based (async) interface.

**Comment by inigomedina** [comment]
I’m closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!

**Comment by strk** [comment]
I personally don't  use CartoDB anymore so no issue here, but IIRC the
lack of session reset was one of security (ie: user X could
control/modify session of user Y)
